image: ruby:2.6

build:
  stage: "build"
  script: "./do build"
  cache:
    paths:
      - "build/"
      - "vendor/"
  artifacts:
    paths:
      - "build/"

deploy:
  stage: "deploy"
  script: "./do deploy"
  needs:
    - "build"
